# Generated by Django 3.0.7 on 2020-06-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architect',
            old_name='user',
            new_name='architect',
        ),
    ]
