# Generated by Django 3.0.7 on 2020-07-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200619_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
