# Generated by Django 2.1.7 on 2020-05-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HogaresYObrasMexicanas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name_plural': 'Unidades'},
        ),
        migrations.RenameField(
            model_name='unidad',
            old_name='costo',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='unidad',
            name='precio_unitario',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
