# Generated by Django 2.1.7 on 2020-05-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HogaresYObrasMexicanas', '0002_auto_20200518_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
